#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _dedupe_keep_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for x in items:
        s = str(x).strip()
        if not s or s in seen:
            continue
        seen.add(s)
        out.append(s)
    return out


def _write_slice(path: Path, label: str, trade_ids: list[str], contexts: list[str]) -> None:
    payload = {
        "slice_label": label,
        "include_trade_ids": _dedupe_keep_order(trade_ids),
        "include_contexts": _dedupe_keep_order([c.lower() for c in contexts]),
        "notes": "Autogenerated failure archetype slice",
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Build failure archetype slices from audit artifacts")
    ap.add_argument("--green-loss-audit", default="control/aee_green_loss_audit_active.json")
    ap.add_argument("--trade-sample", default="control/trade_evidence_sample_active.json")
    ap.add_argument("--out-dir", default="control/failure_slices")
    ap.add_argument("--max-per-slice", type=int, default=120)
    args = ap.parse_args()

    root = Path(__file__).resolve().parent.parent
    gl_path = Path(args.green_loss_audit)
    if not gl_path.is_absolute():
        gl_path = (root / gl_path).resolve()
    ts_path = Path(args.trade_sample)
    if not ts_path.is_absolute():
        ts_path = (root / ts_path).resolve()

    if not gl_path.exists():
        raise SystemExit(f"ERROR: missing green loss audit file: {gl_path}")
    if not ts_path.exists():
        raise SystemExit(f"ERROR: missing trade sample file: {ts_path}")

    gl = _load_json(gl_path)
    ts = _load_json(ts_path)

    green_then_loss = list(gl.get("green_then_loss_samples") or [])
    bankable_losses = list(gl.get("bankable_green_loss_samples") or [])
    winners = list(ts.get("winners") or [])
    losers = list(ts.get("losers") or [])

    max_n = max(1, int(args.max_per_slice))

    fake_runner_rows = [r for r in winners if str(r.get("winner_taxonomy", "")) == "fake_runner"]
    overhold_rows = [r for r in winners if str(r.get("winner_taxonomy", "")) == "overheld_winner"]

    reclaim_stall_rows = [
        r for r in green_then_loss
        if str(r.get("economic_state", "")) == "GREEN_UNPROTECTED"
        and str(r.get("path_shape", "")) == "slow_grind_then_reverse"
    ]

    whipsaw_rows = [
        r for r in green_then_loss
        if str(r.get("path_shape", "")) == "healthy_push_then_full_reversal"
    ]

    green_loss_rows = bankable_losses or green_then_loss

    out_dir = Path(args.out_dir)
    if not out_dir.is_absolute():
        out_dir = (root / out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    slices: list[tuple[str, list[dict[str, Any]]]] = [
        ("fake_runner_slice", fake_runner_rows),
        ("overhold_slice", overhold_rows),
        ("green_loss_slice", green_loss_rows),
        ("reclaim_stall_slice", reclaim_stall_rows),
        ("whipsaw_miss_slice", whipsaw_rows),
    ]

    index_rows: list[dict[str, Any]] = []
    for label, rows in slices:
        rows = rows[:max_n]
        trade_ids = [str(r.get("trade_id", "")).strip() for r in rows if str(r.get("trade_id", "")).strip()]
        contexts = [str(r.get("context", "")).strip() for r in rows if str(r.get("context", "")).strip()]

        out_path = out_dir / f"{label}.json"
        _write_slice(out_path, label, trade_ids, contexts)

        index_rows.append(
            {
                "slice": label,
                "path": str(out_path),
                "trade_id_count": len(_dedupe_keep_order(trade_ids)),
                "context_count": len(_dedupe_keep_order(contexts)),
            }
        )

    index_payload = {
        "generated_from": {
            "green_loss_audit": str(gl_path),
            "trade_sample": str(ts_path),
        },
        "slices": index_rows,
    }
    index_path = out_dir / "index.json"
    index_path.write_text(json.dumps(index_payload, indent=2), encoding="utf-8")

    print(f"Wrote: {index_path}")
    for row in index_rows:
        print(
            f"- {row['slice']}: trades={row['trade_id_count']} contexts={row['context_count']} ({row['path']})"
        )


if __name__ == "__main__":
    main()
